#!/bin/sh

# Create the necessary file structure for /dev/net/tun
# required to run on docker swarm, as there are no devices available
if ( [ ! -c /dev/net/tun ] ); then
  if ( [ ! -d /dev/net ] ); then
    mkdir -m 755 /dev/net
  fi
  mknod /dev/net/tun c 10 200
  chmod 0755 /dev/net/tun
  echo "Created /dev/net/tun."
fi


# Connect to riseup VPN
/app/vpngate-client &


if [ -n "$DNS_SERVERS_OVERRIDE" ]; then
  cp /etc/resolv.conf /etc/resolv.conf.bak
  echo "$DNS_SERVERS_OVERRIDE" | sed -e 's/^/nameserver /' -e 's/,/\nnameserver /' > /etc/resolv.conf
fi


# Setup route for host network
if [ -n "$HOST_NETWORK" ]; then
  gw=$(ip route | awk '$1 == "default" { print $3 }')
  ip route add "$HOST_NETWORK" via "$gw"
fi

# Start Privoxy
ln -s /etc/privoxy/templates /app/riseupvpn/
exec privoxy --no-daemon
